_base_:
  - ../_base.yaml

projection:
  oblique:
    # Set to affine or collinearity to force a single projection path globally.
    method: affine
    # avg_alt: 37.5
    ray_dsm_max_iter: 10
    ray_dsm_tol: 1.0
    ray_dsm_init_window: 9
    ray_dsm_fallback_avg_alt: false
    enable_alt_filter: true
    min_control_points: 3
    pose_csv: "/data/dataset/PV/003-XinXie/CAM/pose.csv"
    dsm_path: "/data/dataset/PV/003-XinXie/dsm/DSM.tif"
    preload_dsm: true
    epsg: 4550

  score:
    mode: standard
    score_threshold: 0.7
    target_length: 2.17
    target_width: 1.10
    area_beta: 0.25
    ratio_beta: 0.2
    shape_beta: 0.1
    w_area: 10.0
    w_ratio: 5.0
    w_shape: 5.0
  
