_base_:
  - ./base.yaml

pipeline:
  run_inference: true

data:
  data_root: "/data/dataset/PV/003-XinXie/"
  image_path:
    - "dom/DOM.tif"


postprocess:
  view_selection:
    enabled: false
  multiview:
    enabled: true
    strategy: nms_keep_max
    score_field: con_weight
    iou_threshold: 0.2
  dom_merge:
    enabled: false

projection:
  mode: dom


output:
  per_image_shp_dir: /data/dataset/PV/ZS_PV/003-XinXie/dom/
  final_merged_shp: /data/dataset/PV/ZS_PV/003-XinXie/dom/dom_merged.shp