_base_:
  - "./base.yaml"

pipeline:
  run_inference: false
  run_projection: true
  run_postprocess: true

data:
  data_root: "/data/dataset/PV/004-CangFang/"
  image_glob: "images/*.JPG"


projection:
  oblique:
    method: slope_correction # ["collinearity", "affine", "slope_correction"]
    # avg_alt: 37.5
    sample_interval: 5
    max_alt_diff: 0.6
    search_margin_px: 0
    ray_dsm_max_iter: 10
    ray_dsm_tol: 0.25
    ray_dsm_init_window: 9
    ray_dsm_fallback_avg_alt: false
    enable_alt_filter: true
    min_control_points: 3
    slope_correction:
      ransac_inlier_threshold: 0.2
      ransac_max_trials: 100
      min_inliers: 5
      max_tilt_deg: 60

postprocess:
  per_image_nms:
    enabled: true
    backend: auto
    score_field: con_weight
    iou_threshold: 0.2
    use_geometry_iou: false

  view_selection: 
    enabled: true
    view_num: 5
    distance_threshold: 0.5
    random_seed: 42

  multiview:
    enabled: true
    strategy: nms_keep_max
    score_field: con_weight
    iou_threshold: 0.2

  prompt_export:
    enabled: true
    mode: oblique
    output_dir: /data/dataset/PV/ZS_PV/004-CangFang/iter_1/views/view_5/prompts_mv_voting_slope_correction/
    min_size: 50
    include_intersections: true
    use_spatial_index: true
    min_confidence: 0.6

  dom_merge:
    enabled: false

output:
  per_image_shp_dir: /data/dataset/PV/ZS_PV/004-CangFang/iter_1/views/view_5/proj_mv_voting_slope_correction/
  per_image_raw_shp_dir: /data/dataset/PV/ZS_PV/004-CangFang/iter_1/views/view_5/infer_mv_voting_slope_correction/
  final_merged_shp: /data/dataset/PV/ZS_PV/004-CangFang/iter_1/views/view_5/view_5_mv_voting_slope_correction.shp
  trace_exports:
    enabled: true
    collected_shp: /data/dataset/PV/ZS_PV/004-CangFang/iter_1/views/view_5/view_5_collected_slope_correction.shp
    selected_shp: /data/dataset/PV/ZS_PV/004-CangFang/iter_1/views/view_5/view_5_selected_mv_voting_slope_correction.shp
  